apiVersion: v1
kind: Service
metadata:
  name: barbara-yo
spec:
  ports:
  - name: ssh-port
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: p2p
    port: 10300 
    protocol: TCP
    targetPort: 10300 
  - name: rpc
    port: 10301
    protocol: TCP
    targetPort: 10301
  selector:
    run: barbara-yo
  type: LoadBalancer
