apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: notary-yo
  name: notary-yo
spec:
  containers:
  - image: irvnet/notary-yo
    name: notary-yo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
